# Generated by Django 5.0 on 2024-02-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Не удалось отправить'), ('pending', 'В ожидании')], default='pending', max_length=50, verbose_name='статус попытки'),
        ),
    ]
